// Auto-generated by capman from OpenAPI spec
// Review and adjust before committing

module.exports = {
  app: 'swagger-petstore-openapi-3-0',
  baseUrl: '/api/v3',
  capabilities: [
    {
      id: 'add_pet',
      name: 'Add a new pet to the store.',
      description: 'Add a new pet to the store.',
      examples: [
        'Add a new pet to the store.',
        'Add a new pet to the store'
      ],
      params: [],
      returns: [
        'pet'
      ],
      resolver: {
        type: 'api',
        endpoints: [
          {
            method: 'POST',
            path: '/pet'
          }
        ]
      },
      privacy: {
        level: 'user_owned'
      }
    },
    {
      id: 'update_pet',
      name: 'Update an existing pet.',
      description: 'Update an existing pet by Id.',
      examples: [
        'Update an existing pet.',
        'Update an existing pet by Id'
      ],
      params: [],
      returns: [
        'pet'
      ],
      resolver: {
        type: 'api',
        endpoints: [
          {
            method: 'PUT',
            path: '/pet'
          }
        ]
      },
      privacy: {
        level: 'user_owned'
      }
    },
    {
      id: 'find_pets_by_status',
      name: 'Finds Pets by status.',
      description: 'Multiple status values can be provided with comma separated strings.',
      examples: [
        'Finds Pets by status.',
        'Multiple status values can be provided with comma separated strings',
        'Finds Pets by status. by status'
      ],
      params: [
        {
          name: 'status',
          description: 'Status values that need to be considered for filter',
          required: true,
          source: 'user_query'
        }
      ],
      returns: [
        'findByStatus'
      ],
      resolver: {
        type: 'api',
        endpoints: [
          {
            method: 'GET',
            path: '/pet/findByStatus'
          }
        ]
      },
      privacy: {
        level: 'user_owned'
      }
    },
    {
      id: 'find_pets_by_tags',
      name: 'Finds Pets by tags.',
      description: 'Multiple tags can be provided with comma separated strings. Use tag1, tag2, tag3 for testing.',
      examples: [
        'Finds Pets by tags.',
        'Multiple tags can be provided with comma separated strings',
        'Finds Pets by tags. by tags'
      ],
      params: [
        {
          name: 'tags',
          description: 'Tags to filter by',
          required: true,
          source: 'user_query'
        }
      ],
      returns: [
        'findByTags'
      ],
      resolver: {
        type: 'api',
        endpoints: [
          {
            method: 'GET',
            path: '/pet/findByTags'
          }
        ]
      },
      privacy: {
        level: 'user_owned'
      }
    },
    {
      id: 'get_pet_by_id',
      name: 'Find pet by ID.',
      description: 'Returns a single pet.',
      examples: [
        'Find pet by ID.',
        'Returns a single pet',
        'Find pet by ID. by pet id'
      ],
      params: [
        {
          name: 'pet_id',
          description: 'ID of pet to return',
          required: true,
          source: 'user_query'
        }
      ],
      returns: [
        'pet'
      ],
      resolver: {
        type: 'api',
        endpoints: [
          {
            method: 'GET',
            path: '/pet/{petId}'
          }
        ]
      },
      privacy: {
        level: 'user_owned'
      }
    },
    {
      id: 'update_pet_with_form',
      name: 'Updates a pet in the store with form data.',
      description: 'Updates a pet resource based on the form data.',
      examples: [
        'Updates a pet in the store with form data.',
        'Updates a pet resource based on the form data',
        'Updates a pet in the store with form data. by pet id'
      ],
      params: [
        {
          name: 'pet_id',
          description: 'ID of pet that needs to be updated',
          required: true,
          source: 'user_query'
        },
        {
          name: 'name',
          description: 'Name of pet that needs to be updated',
          required: false,
          source: 'user_query'
        },
        {
          name: 'status',
          description: 'Status of pet that needs to be updated',
          required: false,
          source: 'user_query'
        }
      ],
      returns: [
        'pet'
      ],
      resolver: {
        type: 'api',
        endpoints: [
          {
            method: 'POST',
            path: '/pet/{petId}'
          }
        ]
      },
      privacy: {
        level: 'user_owned'
      }
    },
    {
      id: 'delete_pet',
      name: 'Deletes a pet.',
      description: 'Delete a pet.',
      examples: [
        'Deletes a pet.',
        'Delete a pet',
        'Deletes a pet. by pet id'
      ],
      params: [
        {
          name: 'pet_id',
          description: 'Pet id to delete',
          required: true,
          source: 'user_query'
        }
      ],
      returns: [
        'pet'
      ],
      resolver: {
        type: 'api',
        endpoints: [
          {
            method: 'DELETE',
            path: '/pet/{petId}'
          }
        ]
      },
      privacy: {
        level: 'user_owned'
      }
    },
    {
      id: 'upload_file',
      name: 'Uploads an image.',
      description: 'Upload image of the pet.',
      examples: [
        'Uploads an image.',
        'Upload image of the pet',
        'Uploads an image. by pet id'
      ],
      params: [
        {
          name: 'pet_id',
          description: 'ID of pet to update',
          required: true,
          source: 'user_query'
        },
        {
          name: 'additional_metadata',
          description: 'Additional Metadata',
          required: false,
          source: 'user_query'
        }
      ],
      returns: [
        'uploadImage'
      ],
      resolver: {
        type: 'api',
        endpoints: [
          {
            method: 'POST',
            path: '/pet/{petId}/uploadImage'
          }
        ]
      },
      privacy: {
        level: 'user_owned'
      }
    },
    {
      id: 'get_inventory',
      name: 'Returns pet inventories by status.',
      description: 'Returns a map of status codes to quantities.',
      examples: [
        'Returns pet inventories by status.',
        'Returns a map of status codes to quantities'
      ],
      params: [],
      returns: [
        'inventory'
      ],
      resolver: {
        type: 'api',
        endpoints: [
          {
            method: 'GET',
            path: '/store/inventory'
          }
        ]
      },
      privacy: {
        level: 'user_owned'
      }
    },
    {
      id: 'place_order',
      name: 'Place an order for a pet.',
      description: 'Place a new order in the store.',
      examples: [
        'Place an order for a pet.',
        'Place a new order in the store'
      ],
      params: [],
      returns: [
        'order'
      ],
      resolver: {
        type: 'api',
        endpoints: [
          {
            method: 'POST',
            path: '/store/order'
          }
        ]
      },
      privacy: {
        level: 'user_owned'
      }
    },
    {
      id: 'get_order_by_id',
      name: 'Find purchase order by ID.',
      description: 'For valid response try integer IDs with value <= 5 or > 10. Other values will generate exceptions.',
      examples: [
        'Find purchase order by ID.',
        'For valid response try integer IDs with value <= 5 or > 10',
        'Find purchase order by ID. by order id'
      ],
      params: [
        {
          name: 'order_id',
          description: 'ID of order that needs to be fetched',
          required: true,
          source: 'user_query'
        }
      ],
      returns: [
        'order'
      ],
      resolver: {
        type: 'api',
        endpoints: [
          {
            method: 'GET',
            path: '/store/order/{orderId}'
          }
        ]
      },
      privacy: {
        level: 'user_owned'
      }
    },
    {
      id: 'delete_order',
      name: 'Delete purchase order by identifier.',
      description: 'For valid response try integer IDs with value < 1000. Anything above 1000 or non-integers will generate API errors.',
      examples: [
        'Delete purchase order by identifier.',
        'For valid response try integer IDs with value < 1000',
        'Delete purchase order by identifier. by order id'
      ],
      params: [
        {
          name: 'order_id',
          description: 'ID of the order that needs to be deleted',
          required: true,
          source: 'user_query'
        }
      ],
      returns: [
        'order'
      ],
      resolver: {
        type: 'api',
        endpoints: [
          {
            method: 'DELETE',
            path: '/store/order/{orderId}'
          }
        ]
      },
      privacy: {
        level: 'user_owned'
      }
    },
    {
      id: 'create_user',
      name: 'Create user.',
      description: 'This can only be done by the logged in user.',
      examples: [
        'Create user.',
        'This can only be done by the logged in user'
      ],
      params: [],
      returns: [
        'user'
      ],
      resolver: {
        type: 'api',
        endpoints: [
          {
            method: 'POST',
            path: '/user'
          }
        ]
      },
      privacy: {
        level: 'user_owned'
      }
    },
    {
      id: 'create_users_with_list_input',
      name: 'Creates list of users with given input array.',
      description: 'Creates list of users with given input array.',
      examples: [
        'Creates list of users with given input array.',
        'Creates list of users with given input array'
      ],
      params: [],
      returns: [
        'createWithList'
      ],
      resolver: {
        type: 'api',
        endpoints: [
          {
            method: 'POST',
            path: '/user/createWithList'
          }
        ]
      },
      privacy: {
        level: 'user_owned'
      }
    },
    {
      id: 'login_user',
      name: 'Logs user into the system.',
      description: 'Log into the system.',
      examples: [
        'Logs user into the system.',
        'Log into the system'
      ],
      params: [
        {
          name: 'username',
          description: 'The user name for login',
          required: false,
          source: 'user_query'
        },
        {
          name: 'password',
          description: 'The password for login in clear text',
          required: false,
          source: 'user_query'
        }
      ],
      returns: [
        'login'
      ],
      resolver: {
        type: 'api',
        endpoints: [
          {
            method: 'GET',
            path: '/user/login'
          }
        ]
      },
      privacy: {
        level: 'user_owned'
      }
    },
    {
      id: 'logout_user',
      name: 'Logs out current logged in user session.',
      description: 'Log user out of the system.',
      examples: [
        'Logs out current logged in user session.',
        'Log user out of the system'
      ],
      params: [],
      returns: [
        'logout'
      ],
      resolver: {
        type: 'api',
        endpoints: [
          {
            method: 'GET',
            path: '/user/logout'
          }
        ]
      },
      privacy: {
        level: 'user_owned'
      }
    },
    {
      id: 'get_user_by_name',
      name: 'Get user by user name.',
      description: 'Get user detail based on username.',
      examples: [
        'Get user by user name.',
        'Get user detail based on username',
        'Get user by user name. by username'
      ],
      params: [
        {
          name: 'username',
          description: 'The name that needs to be fetched. Use user1 for testing',
          required: true,
          source: 'user_query'
        }
      ],
      returns: [
        'user'
      ],
      resolver: {
        type: 'api',
        endpoints: [
          {
            method: 'GET',
            path: '/user/{username}'
          }
        ]
      },
      privacy: {
        level: 'user_owned'
      }
    },
    {
      id: 'update_user',
      name: 'Update user resource.',
      description: 'This can only be done by the logged in user.',
      examples: [
        'Update user resource.',
        'This can only be done by the logged in user',
        'Update user resource. by username'
      ],
      params: [
        {
          name: 'username',
          description: 'name that need to be deleted',
          required: true,
          source: 'user_query'
        }
      ],
      returns: [
        'user'
      ],
      resolver: {
        type: 'api',
        endpoints: [
          {
            method: 'PUT',
            path: '/user/{username}'
          }
        ]
      },
      privacy: {
        level: 'user_owned'
      }
    },
    {
      id: 'delete_user',
      name: 'Delete user resource.',
      description: 'This can only be done by the logged in user.',
      examples: [
        'Delete user resource.',
        'This can only be done by the logged in user',
        'Delete user resource. by username'
      ],
      params: [
        {
          name: 'username',
          description: 'The name that needs to be deleted',
          required: true,
          source: 'user_query'
        }
      ],
      returns: [
        'user'
      ],
      resolver: {
        type: 'api',
        endpoints: [
          {
            method: 'DELETE',
            path: '/user/{username}'
          }
        ]
      },
      privacy: {
        level: 'user_owned'
      }
    }
  ]
}
