#!/usr/bin/env node
'use strict'

const fs   = require('fs')
const path = require('path')

const pkg     = require('../package.json')
const version = pkg.version

const output = `// Auto-generated by scripts/version.js — do not edit manually
export const VERSION = '${version}'
`

const outPath = path.join(__dirname, '..', 'src', 'version.ts')
fs.writeFileSync(outPath, output)
console.log(`version.ts updated to ${version}`)